### ISSUE TITLE
Surface Book 1 - need help

### ISSUE THREAD

**Issue by drvuxe** [DreamWalkerXZ/Surface-Pro-4-Hackintosh-i7#3]
I use this EFI for surface book 1 and everything run smooth but can't play video from youtube. I think that have to do with graphic issue.

my surface book 1
i7-6600u  intel 520 with dgpu nvida 960m
256gb ssd and 8gb RAM

thank you for your time and support.

**Comment by DreamWalkerXZ** [comment]
Sorry. This EFI is not intended for surface book 1. It will be hard for me to solve it for you since I don't have that machine.
